### ISSUE TITLE
The problem of running http://localhost:9000/convert/document.docx

### ISSUE THREAD

**Issue by ghost** [andreysaf/nodejs-convert-file-server#4]
When I run http://localhost:9000/convert/document.docx, it occurs bugs below

(node:4008) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received an instance of Error
    at ServerResponse.end (_http_outgoing.js:745:13)
    at D:\demo\nodejs-convert-file-server-master\app.js:272:11
(node:4008) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:4008) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Could you help me to fix this bug, thanks in advance!

**Comment by andreysaf** [comment]
Hello @xiaopengguo1406! Did you end up resolving it? Let me know if you need help.

**Comment by xiaopengguo1406** [comment]
> Hello @xiaopengguo1406! Did you end up resolving it? Let me know if you need 


> Hello @xiaopengguo1406! Did you end up resolving it? Let me know if you need help.
I have resolve this problem via reinstallation. Thank you for your elegent project!

**Comment by ghost** [comment]
I have resolved this problem via reinstallation. Thank you for your elegent project!
