### ISSUE TITLE
Convert from docx to pdf. 

### ISSUE THREAD

**Issue by Konu33** [andreysaf/nodejs-convert-file-server#7]
![image](https://user-images.githubusercontent.com/38396204/96725110-d72aa480-13b0-11eb-9c79-fa0274ca50d5.png)
Code is exactly same as in your github repository. 

When I run npm test
![image](https://user-images.githubusercontent.com/38396204/96725917-be6ebe80-13b1-11eb-9049-f5cdf9c39286.png)

**Comment by andreysaf** [comment]
Thanks for reaching out! 

I did the clean check out on Mac OS Catalina and it ran okay:
![image](https://user-images.githubusercontent.com/6531389/96749521-c9106000-137f-11eb-8eb7-2a5a84fb123c.png)

The error you are getting is the path not being resolved correctly. For example, I do not see text.docx under files. Please verify that inputPath resolved correctly and the file is present. 

If you just download the .zip of the repo and run `npm i` and `npm run test` does it work?

**Comment by andreysaf** [comment]
Just tried it on a Windows machine as well:

```λ npm run test

> nodejs-custom-server@1.0.0 test C:\Users\Correy\projects\pdftron\nodejs-convert-file-server
> mocha --timeout 10000



  /GET files
    √ it should GET files
    √ it should GET webviewer.pdf

  /GET optimize/filename

PDFNet is running in demo mode.
Permission: read
Permission: optimizer
Permission: write
    √ it should GET optimized PDF file (821ms)

  /GET thumbnail/filename
Permission: rast
    √ it should GET a thumbnail of a PDF file (97ms)

  /GET convert/filename
    √ it should GET a converted PDF document (3756ms)

  /GET convertHTML/filename
Permission: html2pdf
    √ it should GET a converted PDF document from HTML (1742ms)

  /GET generate/filename
    √ it should GET a newly generated PDF document

  /GET textExtract/filename
Permission: textext
    √ it should GET text from PDF page 1

  /GET replaceContent/filename
    √ it should GET a newly generated PDF document with strings replaced (67ms)

  /GET watermark/filename
    √ it should GET a watermarked PDF document (46ms)


  10 passing (7s)```

**Comment by Konu33** [comment]
![image](https://user-images.githubusercontent.com/38396204/96875080-1e7b6880-1477-11eb-88f6-218878579ad9.png)

Problem occurs for app which runs inside docker container.

To have all dependencies I run commands like this.

RUN apt-get update || : && apt-get install python -y

RUN apt-get update && apt-get install make

RUN apt-get update && \
    apt-get -y install gcc mono-mcs && \
    rm -rf /var/lib/apt/lists/* 



Locally it`s works but with docker there is few problems

**Comment by andreysaf** [comment]
> ![image](https://user-images.githubusercontent.com/38396204/96875080-1e7b6880-1477-11eb-88f6-218878579ad9.png)
> 
> Problem occurs for app which runs inside docker container.
> 
> To have all dependencies I run commands like this.
> 
> RUN apt-get update || : && apt-get install python -y
> 
> RUN apt-get update && apt-get install make
> 
> RUN apt-get update &&
> apt-get -y install gcc mono-mcs &&
> rm -rf /var/lib/apt/lists/*
> 
> Locally it`s works but with docker there is few problems

Hey, thanks for the commands to make it work! I can make updates to README and give you credit. 

I am not too familiar with Docker, but is the container not dependant on the OS and the command you provided should work regardless of host?
